### ISSUE TITLE
MWC MQS restart with network outage

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#114]
Hi @cgilliard,  mwc qms doesn't detect reconnect form the same wallet. With network issues you can report incorrectly that 
new login detected. mwcmqs listener will stop!

Step to reproduce:
wallet713> listen
starting mwcmqs listener...
wallet713>
mwcmqs listener started for: [xmjJGkX9U75Vo8Ro26gTm2i4k4CD39Q24qvQqAPeQVeWuo36YVFh]
wallet713>

Turn OFF wifi

wallet713> stop
stopping mwcmqs listener...
wallet713>

Turn ON wifi

wallet713> listen
starting mwcmqs listener...
wallet713>
mwcmqs listener started for: [xmjJGkX9U75Vo8Ro26gTm2i4k4CD39Q24qvQqAPeQVeWuo36YVFh]
ERROR: new login detected. mwcmqs listener will stop!
mwcmqs listener [xmjJGkX9U75Vo8Ro26gTm2i4k4CD39Q24qvQqAPeQVeWuo36YVFh] stopped
wallet713>

Also the order of messages is not always the same. It is possible to get in better way that I can handle:
ERROR: new login detected. mwcmqs listener will stop!
mwcmqs listener [xmjJGkX9U75Vo8Ro26gTm2i4k4CD39Q24qvQqAPeQVeWuo36YVFh] stopped
mwcmqs listener started for: [xmjJGkX9U75Vo8Ro26gTm2i4k4CD39Q24qvQqAPeQVeWuo36YVFh]

Unfortunately order can vary

**Comment by cgilliard** [comment]
I can reproduce this issue, but it only happens if you call stop before mwc713 detects that it's disconnected. If you do call stop, the problem is that it takes up to two minutes for the listener to actually stop in this case because it relies on the timeout. That is why you are seeing that you are already logged in because your connection never disconnected. I will see If I can send an interrupt to make it happen faster. I also should prevent you from calling listen until the old thread ends.

**Comment by cgilliard** [comment]
Unfortunately, looks like Rust doesn't have interrupts like Java does:

https://stackoverflow.com/questions/52465480/what-is-the-standard-way-to-get-a-rust-thread-out-of-blocking-operations

Maybe the best I can do is prevent you from starting the listener until the old one ends. This will generally be very fast, unless your network connection is down in which case there might be a small delay to wait for the 2 minute timeout. I think this is ok.

**Comment by bayk** [comment]
We can do waiting for disconnect and start listener after. 
The only problem that if user press the button 'Stop', he expects some respond now. If we need to wait, we should show a message about that and that will be modal message box.
Looks like it is the best what we can do. Chris, what do you think about that?

**Comment by cgilliard** [comment]
Per discussion in discord:
1.) Added WARNING message if stop failed due to network connectivity issue.
2.) Added TID to listener start/stop messages.
3.) Suppressed ERROR: new login detected. message in case of new thread kicking out old thread.

Note: ordering is still not guaranteed due to the async threads.

Example start/stop:

wallet713> listen
starting mwcmqs listener...
wallet713> 
mwcmqs listener started for: [xmgehLCvsHXdoAenuUARvQGMPkzJdm5Qb1wTQVi2WnRaSjC1CWgH] tid=[LesFyf9GRfCw8i1VjYb3f]
wallet713> 
wallet713> 
wallet713> stop
stopping mwcmqs listener...
wallet713> 
mwcmqs listener [xmgehLCvsHXdoAenuUARvQGMPkzJdm5Qb1wTQVi2WnRaSjC1CWgH] stopped. tid=[LesFyf9GRfCw8i1VjYb3f]

**Comment by cgilliard** [comment]
Keeping open for updates to mwc-qt-wallet.

**Comment by bayk** [comment]
Hi @cgilliard , at mwc713  I will add  tid=[LesFyf9GRfCw8i1VjYb3f]   to all mwcmqs related activity messages. tid need to be there since model underneath 'many'. I will push the changes soon.
