### ISSUE TITLE
New Wallet Password Matching Confirmation

### ISSUE THREAD

**Issue by pocketLNio** [mwcproject/mwc-qt-wallet#116]
During new wallet creation, user is prompted to create a wallet password, as the password entry is obfuscated, it will be great is the confirmation field is tagged with a 'check mark' or a cross indicating the password confirmation entry is matching the initial entry.

**Comment by bayk** [comment]
Yes, make sense.

**Comment by bayk** [comment]
Hi @condensed-io , here are the screenshots, please you can check the icons. I reuse some of that we already have.  

![image](https://user-images.githubusercontent.com/42393608/66277442-89013c80-e853-11e9-830a-f4c8964dbe69.png)

![image](https://user-images.githubusercontent.com/42393608/66277454-bcdc6200-e853-11e9-9ad7-7133ba822669.png)

**Comment by cgilliard** [comment]
Looks good functionally, but maybe condensed can provide something that
looks better. Here's one example:
https://www.the-art-of-web.com/html/html5-form-validation/

**Comment by bayk** [comment]
Label must be not embedded into edit control.

**Comment by cgilliard** [comment]
Yes, that's fine just meant more like how it looks. The green check box and
red X are standard.

**Comment by bayk** [comment]
Our color pattern technically has two colors, it is enforced by purple
background. Red will not work at all. Green (light green) will looks like
slightly different then white (we have green "highlights" at node status).
Because of that, most of images from internet doesn't work for us. Brent
might figure out something better, that is why I posted the screenshots for
him.

**Comment by cgilliard** [comment]
Yes, let's wait to hear from Brent. I don't mean to make it look exactly
like that just more of a general idea. It will have to fit in with our
color scheme.
