### ISSUE TITLE
icons dont show up on macbook air

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#129]
See screenshot, can't see radio buttons to select mainnet or floonet.
![Screen Shot 2019-11-10 at 10 07 16 PM](https://user-images.githubusercontent.com/7232183/68564868-a737fa80-0406-11ea-8146-4e6fe0d04522.png)

**Comment by bayk** [comment]
Hi @cgilliard ,  is it your laptop?  Can you try to set QT_SCALE_FACTOR  value to 1.01 or 0.99 and start the wallet.

I mean
> export QT_SCALE_FACTOR="1.01"

That issue happens at Windows and Linux if QT_SCALE_FACTOR not set or 1, but I never see it on Mac. I guess it might because of retina display. Air might not have a retina.

Please let me know if it is possible to try that test.

**Comment by cgilliard** [comment]
I have a macbook pro, but I was trying on my daughter's macbook air. Will
try that.

**Comment by cgilliard** [comment]
When I set export QT_SCALE_FACTOR="1.01" and ran it, the icons show up.

**Comment by bayk** [comment]
Great, now it is clear how to fix. Will try first if it will work on retina.

**Comment by bayk** [comment]
@cgilliard , please check if fix work when you have a chance and than close the issue

**Comment by cgilliard** [comment]
Confirmed fixed on macbook air.
