### ISSUE TITLE
keybase on windows not working for some users

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#130]
<img width="781" alt="Screen Shot 2019-11-11 at 9 33 25 AM" src="https://user-images.githubusercontent.com/7232183/68607814-5821b200-0466-11ea-9dc1-62db0941ea24.png">

**Comment by cgilliard** [comment]
Found that deleting line that says keybase_binary = "keybase" on windows allows mwc713 to start listening.

**Comment by jbyrer** [comment]
Under "wallet config" I had to enter a valid path into the "keybase console client path" field.  Because the default keybase install puts the files under <userhome>\AppData\keybase, and AppData is hidden by default, I had to go in through file explorer and "unhide" the directory, then add it into the "keybase console client path" using the "select" button.  Adding the path manually through cut and paste didn't seem to work.

**Comment by cgilliard** [comment]
Thanks for the details Jim.

**Comment by cgilliard** [comment]
I believe it's fixed here: https://ftp.mwc.mw/nightly_builds/11-12-2019/
Jim is confirming.

**Comment by cgilliard** [comment]
Jim confirmed it was fixed in nightlys.

**Comment by bayk** [comment]
Issue sounds like closed
