### ISSUE TITLE
user requested ability to see block height that txn was confirmed in transaction/output tab.

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#133]

**Comment by bayk** [comment]
Hi @cgilliard , seems like user want to see the height of the output that associated with a transaction.  "Confirmed" flag is calculated by searching for the matching output. Since output has height, it should be doable. 
Also that will have the same limitations that 'Confirmed' has. If output doesn't exist, it will be impossible to calculate the height.

**Comment by bayk** [comment]
Changes are pushed. Will close after build verification. Changes was made at mwc713 as well
