### ISSUE TITLE
user getting "Wallet error" when trying to claim

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#150]
See screenshot and log files.

![photo_2019-12-03 18 08 34](https://user-images.githubusercontent.com/7232183/70106263-f8976c00-15f7-11ea-8032-d7cad09f74f4.jpeg)

**Comment by bayk** [comment]
Here is why the issue happens:

It is normal output for 'getnextkey --amount':

/mw/mwc713/target/release/mwc713 --config ~/mwc-qt-wallet/wallet713v2.toml --disable-history

Welcome to wallet713 for MWC v2.4.8

Unlock your existing wallet or type `init` to initiate a new one
Use `help` to see available commands

ERROR: error: could not unlock wallet! are you using the correct passphrase?
wallet713>
wallet713> init -p  password
**Press ENTER when you have done so**

Your mwcmq address: xmiuyC3sdhXpJnR7pvQ8xNgZLWQRQziZ1FxhEQd8urYWvSusuC69
wallet713> getnextkey --amount 1000000000
.....

Note, "Press ENTER when you have done so" is printed and it is what QT wallet checking for.

Here is problem output (from the logs):

Welcome to wallet713 for MWC v2.4.8
Unlock your existing wallet or type `init` to initiate a new one
Use `help` to see available commands

ERROR: error: could not unlock wallet! are you using the correct passphrase?

CENSORED: init with password (unlock)

**Wallet seed file exists: /Users/michaelgraub/mwc-qt-wallet/gui_wallet713_data/wallet.seed**

wallet713>
....

By some reason mwc713 print that seed already exist instead of "Press ENTER when you have done so"

I will try to reproduce and check if 'press Enter' really needed

**Comment by cgilliard** [comment]
Anyone getting this issue, please upgrade to https://github.com/mwcproject/mwc-qt-wallet/releases/tag/1.0.10
