### ISSUE TITLE
recover from seed autocomplete

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#211]
Currently recover from seed requires you to type the entire seed phrase. It would be better if it would do autocomplete. This is a feature request for that. This may require another option for inputing the seed phrase because currently there is a big text area for the full phrase. This is convenient for some cases, but in some cases people use products that only allow them to write down the first 4 letters of the seed phrase so autocomplete is desirable.

**Comment by bayk** [comment]
Autocomplete can be done for a single word only, not for a whole phrase. 
We do verification for incorrect words, so user can correct it. 

![image](https://user-images.githubusercontent.com/42393608/77687094-2fa0dd00-6f5b-11ea-8958-51202faca708.png)

@cgilliard ,  it is not much what we can do. Instead of 'Your phrase contains non dictionary words: sodier, coper, rceive'  I can print word numbers, so that will be something like this:
Your phrase contains non dictionary words: 4 sodier, 7 coper, 20 rceive

Do you think it will help?
