### ISSUE TITLE
node/mwc-wallet must check IO data symmetrically

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#234]
Example:
fn read_fixed_bytes(&mut self, len: usize) -> Result<Vec<u8>, Error> {
        // not reading more than 100k bytes in a single read
        if len > 100_000 {
            return Err(Error::TooLargeReadErr);
        }
        let mut buf = vec![0; len];
        self.source
            .read_exact(&mut buf)
            .map(move |_| buf)
            .map_err(map_io_err)
    }

There is no checking on write.

Result:  if somebody write the data larger then 100k with success, after reads will always fail. As a result wallet data is corrupted and no way to recover it.

**Comment by cgilliard** [comment]
Note: you can still recover by "restore from seed", but transaction history will be lost.

**Comment by vinayaga07** [comment]
Steps to be followed

1. Install mining wallet, it has about 150k outputs.
here is a seed for it 
2.  With rest API try to do Send for large amount, about 10000 is enough.
3. Check that it will fail because of number of outputs limitation.  That is the first line of defense.
4. Now specify max_output  as a large number. Default is 500. You can do 2000. 2000 outputs should be over the limit of the internal storage. So you suppose to hit that fix
5. You should see different error that said that you can't WRITE to the storage.
If you see, you can't READ - it is an issue.

**Comment by jbyrer** [comment]
Ran using a large send value:
 curl -u mwc:FQJjeSSZAOAPs1G2WRM5 --request POST --data-raw '{"jsonrpc":"2.0","method":"init_send_tx","params":{"args":{"src_acct_name":null,"amount":10000000000000, "minimum_confirmations":1000,"max_outputs":500,"num_change_outputs":1,"selection_strategy_is_use_all":false,"message":"Take money!","target_slate_version":null,"estimate_only":null,"send_args":{"method":"http","dest":"http://10.0.0.20:3415","finalize":true,"post_tx":true,"fluff":false},"exclude_change_outputs":false, "minimum_confirmations_change_outputs": 2,"payment_proof_recipient_address":null,"ttl_blocks":1000}},"id":1}' http://127.0.0.1:3420/v2/owner

{
  "id": 1,
  "jsonrpc": "2.0",
  "result": {
    "Err": {
      "TooLargeSlate": 500
    }
  }
}

Ran using a smaller value and was successfull, as expected.
