### ISSUE TITLE
Wallet crash

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#276]
User reported crash on mac when moving funds.

**Comment by cgilliard** [comment]
[message (20).txt](https://github.com/mwcproject/mwc-qt-wallet/files/4558763/message.20.txt)

**Comment by scasaletto** [comment]
[wallet-crash.txt](https://github.com/mwcproject/mwc-qt-wallet/files/4583873/wallet-crash.txt)

Hit same crash as user on Mac.

**Comment by scasaletto** [comment]
Tracked crash down to Account Transfer window's vector of AccountInfo objects getting overwritten while the transfer is being processed. This occurs when the Setting button is selected as it cause updateWalletBalance to be called. In the background, the balance is coming in and the window's updateAccounts() method is called and wipes out the original vector of accountInfo objects. K says he will fix my changing the event processing to occur on the UI thread. So reassigning to him.

**Comment by bayk** [comment]
All our events are processed at a main thread, that wasn't issue.
The problem was a UI loop. Any UI operation starts event loop that fetch new messages and apply changes. So even it a single thread, it is event driven, so it can be interrupted.
In short - it is not safe to use reference if you can be interrupted.
Also, I believe crash happens if you see some message during the transfer, like MQS is not running or another operation in the progress.

**Comment by vinayaga07** [comment]
Have followed the following steps and not observed any issue. Hence closing this ticket.

In the account funds transfer window, select the button to change the send settings. Change your confirmations and then save. Then quickly select to send the funds between accounts.
