### ISSUE TITLE
[QT-Wallet] Warning message need to be updated.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#319]
**Description:**
Currently the warning message displays "Stopping process mwc713 is taking longer.......", instead it should be "MWC-Qt-Wallet is taking longer to exit...."

Please refer screenshot for more details.
![image](https://user-images.githubusercontent.com/63310656/81725758-f2a98f00-94a3-11ea-97b9-e75df8013e17.png)

**Comment by vinayaga07** [comment]
In the recent build, observed the same error message, hence re-opening the ticket.

![image](https://user-images.githubusercontent.com/63310656/82925115-f0166180-9f9a-11ea-8188-89cf5ab1ffb3.png)

**Comment by bayk** [comment]
We can't change message to 'MWC-Qt-Wallet is taking longer to exit'  because stopping process can happens at any time. 
Issue might happen because there are some tasks in the queue and we need to wait until they will be finished. I don't want to drop the tasks, because somebody might wait for the responds.
We probably should increase a timeout.

**Comment by vinayaga07** [comment]
Closing this ticket, as per the above comments.
