### ISSUE TITLE
Selecting account in Send window changes back to original account

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#349]
In the Send window, when you select a different account than the one that was displayed when you first entered the window, the original account will be restored after about 30-60 seconds.

**Comment by bayk** [comment]
This issue is bigger then explained and also releted to receive account as well.
How qt wallet should handle that:
1. Receive account should be stored per wallet. When user start qt wallet, it should setup receive account as it was done last time. 
2. Current account should be used for all pages that using account: send, transactions and outputs. And also it should be stored per wallet.

Testing scenarios:
1. Open qt wallet, wallet 1. Setup receive account,  at pages send, transactions and outputs select current account and check if selection is correct.
2. restart qt wallet and check that receive account and current accounts are restored.
3. Open another wallet 2 and check that receive account and current accounts are different and they stored and restored correctly.
4. Do some account transfers. Check if account transfer affect  receive and current accounts.

**Comment by jbyrer** [comment]
OS tested: OSX

How to reproduce: Have a wallet with multiple accounts open.  Go to the outputs tab and change to a non default account.  Switch to the receive tab.

Behavior: The receive field does not get updated.

Expected Behavior: The receive field should be updated.

**Comment by jbyrer** [comment]
Tested as instructed.  The receive tab doesn't change, but Chris said that is expected.  Closing unless I hear anything from Konstantin conflicting.

**Comment by bayk** [comment]
@jbyrer , Receive is different, it shouldn't change.  There you define account that accept the coins.  This account should not be changed when you checking your transactions or sending coins.
So it is feature, it is expected that way

**Comment by jbyrer** [comment]
closed as K agreed that receive should be different (as it is)
