### ISSUE TITLE
Sending some coins results in 0 spendable coins

### ISSUE THREAD

**Issue by privateidentity** [mwcproject/mwc-qt-wallet#367]
Example
Total coins in the wallet are 50
send 10 coins
once the 10 coins are sent the remaining 40 coins are unspendable

The desired behaviour appears to be 40 spendable coins and 10 unspendable coins.

If the confirmations required is set to 1 then this allows the remaining coins to be spendable faster.

The images below show the bug.

![wallet bug after sending coins mcq](https://user-images.githubusercontent.com/64110976/83626695-2aa27e80-a5d9-11ea-8297-59b098bd6f42.PNG)
![appear to be related to confirmations](https://user-images.githubusercontent.com/64110976/83626709-2fffc900-a5d9-11ea-8008-646ba8f72b11.PNG)

**Comment by cgilliard** [comment]
The issue is that your coins are actually represented by outputs. Since you had a 50 MWC output, the entire output had to be locked until the transaction confirmed. There's no way to not lock part of the output. If you had smaller outputs, (like say two 25 MWC outputs) one of them would have been spendable right away, but the other not.
