### ISSUE TITLE
QT wallet header is centered in MAC OS platform, but left aligned in Windows platform.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#373]
**Description:**
QT wallet header is centered in MAC OS platform, where as in Windows platform header is left aligned.
Please refer the below screenshot for more details.

**Expected Result:**
QT-Wallet UI should looks similar irrespective of OS Platforms.

![image](https://user-images.githubusercontent.com/63310656/83671021-a5779380-a5f1-11ea-9a8b-830b209be037.png)

**Comment by bayk** [comment]
Hi Vinayaga, 
we don't control headers, OS can display that as it wants or not display at all.
The same is about system menus. 
For MacOS we was able to change the color of the title. For Windows and Linux we do nothing, so native style is displayed. 
I am closing this ticket because we are not supporting more then QT platform support.
