### ISSUE TITLE
Should Detect not synced up node

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#50]
I think mwc713  should provide more info about the node.

I am trying to send some funds from mwc713 to mwc-wallet  with file.
I did that and there was no error messages.
mwc713 said that transaction is confirmed. But mwc-wallet printed that funds awaiting finalization.

The reason was that for the node it takes time to download all blocks. It is not clean that it is not done. 

NodeInfo command prints Height for itself and for peers.  mwc-qt-wallet need to compare those values and print in status "Syncing".  

Also we should at start check the node status and emit critical level message and maybe show Message Box that explain that users can't trust transaction/output status.

**Comment by cgilliard** [comment]
Also, one thing to understand is that there is no single source of truth.
That's part of how cryptocurrency works. According to the node that mwc713
was connected to (mwc713.mwc.mw which is a very well connected and always
synced node) the transaction is confirmed, but according to your node
(which was not synced yet) the transaction is not confirmed. This is
correct and expected behavior. There's really no way that mwc713 in this
case would know that the receiver's node is not synced since it doesn't
know which node the receiver is connected to.

**Comment by bayk** [comment]
Yes, behavior is expected, but it is hard to spot it with wallet. 
This issue is about detection of that fact that peer node has much higher block height. It is mean that node not in sync yet. That is why user should expect that transactions are not confirmed because of that.

**Comment by cgilliard** [comment]
What we could do if your full node is still in the "syncing" state it reports this to mwc713 and a warning is printed. Another message can be printed when syncing is done.

**Comment by bayk** [comment]
Messages at message box are not user friendly. I think we can eliminate them.
If node out of sync at the start, we can  start from the Node Page, so user will see that node status - out of sync.
If node was at sync and go out of sync during the session. We will print the regular warning. This message in not different from others that mwc713 emitting.
I think that will be more user friendly.

**Comment by cgilliard** [comment]
I meant on mwc713. These can be processed by mwc-qt-wallet as you mentioned.
