### ISSUE TITLE
When restoring wallet, directory name truncated and not updated when changed.

### ISSUE THREAD

**Issue by scasaletto** [mwcproject/mwc-qt-wallet#520]
![Snip20200918_1](https://user-images.githubusercontent.com/7772099/93602170-e076ba80-f987-11ea-82d0-49bc94581d6f.png)

In the above screen shot, you can see that the directory "gui_wallet713_data3", as displayed in the window title, is not what is displayed in the message: "You are saving your data to: ..."  The reason is that the directory name is being truncated.

Also if you try to change the directory name, what is displayed in the "You are saving your data to: " message is not updated.

**Comment by bayk** [comment]
Sharon, change data directory is not just a change. It is reinitiate the whole process. Directory is a starting point, so it can't be changed easily. It is working for me.
Probably the real issue that a directory name is truncated so you don't see the change. Or may be new directory is not selected or ignored.

**Comment by scasaletto** [comment]
Konstantin, You misunderstand. This defect is about longer directory names being truncated. Then when you click change data directory, the directory name is not updated in the message displayed.

**Comment by bayk** [comment]
Is it not updated because of truncate issue?

**Comment by scasaletto** [comment]
No the message was not updated because there just wasn't a call to update the message after change directory was invoked. So if the directory changed, it wasn't reflected in the message which displayed the warning.

**Comment by bayk** [comment]
No update is expected. The dir change is initiate a workflow. So even if
you add an update, you will hide the issue.

**Comment by scasaletto** [comment]
OK, something is wrong with the logic implemented for that screen then. I have not entered my wallet name or password yet. The workflow should not be initiated until the seed is entered. Is there another bug here?

**Comment by bayk** [comment]
You are very welcome to make it better. But please keep in mind that
you have to handle all corner cases. For example, user might select
dir with the wallet data. In this case we should open the wallet, not
create a new one. If that data is corrupted, we should tell the user
about that. There are many such corner case scenarios.
Currently my solution handle that well. If you you decided to change
that, your solution should handle such cases as well. And UI must
adopt for that as well.  Page that create a new wallet different from
the page that open the wallet.  Also, please keep in ming that it
should be friendly to the mobile. You can't come with solution that
need to be duplicated for mobile.
P.S. Mobile for the dir is very minor issue, we are not planning to
have that now, but in the future that might be needed. But since my
solution cover that as well, if you decided to change, please cover
that scenario as well.

**Comment by vinayaga07** [comment]
@hcasalet , @bayk ,
Please let me know, what fix went in with the latest build?

**Comment by scasaletto** [comment]
It turns out that the directory name K was testing with was shorter than mine by only a couple of characters because he uses his last name of "bay". My wallet directory of /Users/sharon/mwc-qt-wallet/gui_wallet713_data was just a couple of characters too long for what was allowed and was being truncated. So I reduced the size of the font used and increased the size of the field so that longer names will not be truncated. However extremely long names will still be truncated as there was only so much room to increase the field size to. So if my home directory was /Users/scasaletto or /Users/sharoncasaletto I think the directory might still be truncated.

**Comment by bayk** [comment]
Yes, it is true. But what can we do with truncation?  Add something like ... ?

**Comment by vinayaga07** [comment]
Verified with the latest build and observed that the wallet directory field font is small and increased field size.
BTW... my wallet directory field is not truncated by now.
