### ISSUE TITLE
[QT0-wallet] While trying to transfer 0.0001 MWC, getting Transaction fee as **unknown** .

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#591]
**Description:**
While trying to transfer 0.0001 MWC, getting Transaction fee as **unknown** .
Please refer below screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/98136020-7a69d680-1ee6-11eb-9e50-692def213ef7.png)

**Comment by vinayaga07** [comment]
**Note:**
Tried to reproduce the same issue on the another wallet but unable to reproduce it.

**Comment by bayk** [comment]
I will check. In theory it should work fine.

**Comment by scasaletto** [comment]
I tried to reproduce on my wallet and could not. The only time we display this fee like this is when we cannot calculate the fee. Chris didn't want us to ever stop a transaction in qt wallet itself and if the transaction was going to fail, mwc713 wallet should catch it. You might get a message like this if you tried to send funds that you did not have available for sending or were locked for some reason.

**Comment by bayk** [comment]
Sending for small amount does work. I tested with 1 nanocoin.

wallet713> slate [bf635021-e8b2-478d-9770-9658156ab734] received from [xminFUjbKtaynDuX9KzSz74RAd5Wj5KeeiQ5cA2i4Z5DFYR3PZFN] for [0.000000001] MWCs.
slate [bf635021-e8b2-478d-9770-9658156ab734] sent back to [xminFUjbKtaynDuX9KzSz74RAd5Wj5KeeiQ5cA2i4Z5DFYR3PZFN] successfully

The issue happens if there is not enough funds for the fee. It is easy to reproduce. And normally if user continue there will be a message 'Not enough funds' from mwc713 wallet.

The real issue is that we don't report error correctly. So the fix will be about the error.

**Comment by bayk** [comment]
Testing:
1.  Try to spend almost all amount, you should see the error message  about the fees.
2.  Move to a separate account amount less then fee ( something like 0.00001 ). You will see the message about that.

**Comment by vinayaga07** [comment]
Verified,
1. Try to spend almost all amount, you should see the error message about the fees.
2. Move to a separate account amount less then fee ( something like 0.00001 ). 

Hence closing this ticket.
