### ISSUE TITLE
[Mobile Wallet] on clicking MWC app, it is getting landed on "Battery optimisation" page

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#678]
**Description:**
In Android Mobile, on clicking MWC app, it is getting landed on "Battery optimisation" page.
On clicking Mobile's Back button again, MWC app Login screen is getting displayed.

![image](https://user-images.githubusercontent.com/63310656/102905914-ddfd9280-4499-11eb-898b-cb1d572f4d81.png)

**Note:**
Able to reproduce this issue back to back

**Comment by bayk** [comment]
@vinayaga07 ,  let's keep it for now. We have battery optimization exemption fir app because we don't want Android control the backend process. With that I was able to send coins to idle device pretty well with tor and about 80% success with MQS. 
We will need to test close to the end if app will work without this optimization exemption. 
If we requesting the exemption at app metafile, this dialog will popup with every run.

**Comment by bayk** [comment]
I removed that feature.  @vinayaga07 , please keep an eye what happens when device is locked, changed etc.  It might start loosing connection because of that. 

Please try to send some coins to your mobile device while it sleeping. Please try both MQS and Tor.  In my tests tor worked better.  It is expected that sometimes send fail, but we need to know how often it will not go through.
