### ISSUE TITLE
Mobile Wallet, the "Notification" page has few critical error messages repeatedly

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#691]
**Description:**
In the Mobile Wallet, the "Notification" page has few critical error messages repeatedly, 

-  "UNABLE TO SWITCH ACCOUNT. UNKNOWN ACCOUNT LABEL".
- "UNKNOWN ACCOUNT LABEL".

**Expected Result:**
These error messages are not expected.

![image](https://user-images.githubusercontent.com/63310656/103788501-e68ec500-5064-11eb-8864-e51f118f186e.png)

**Comment by bayk** [comment]
@vinayaga07 , somehow you created an account with empty name.  How can we reproduce it?  Also do you see this empty  account in account list? 
I think it is not recoverable issue. You will probably need to create another wallet and recover form the seed.

**Comment by vinayaga07** [comment]
Steps to be followed to reproduce the issue.

1. Goto Wallet--> Accounts page
2. Create a new Account
3. Click on the Notification icon.


![image](https://user-images.githubusercontent.com/63310656/107674127-a4d4e800-6cbc-11eb-9f93-23975f1990ea.png)

**Comment by bayk** [comment]
@vinayaga07 , can you reproduce it?  Did you create an account with empty name?

**Comment by vinayaga07** [comment]
@bayk yes, I'm able to reproduce the issue with the recent build. 
Created a new account with the account name and got this issue.

**Comment by vinayaga07** [comment]
Able to reproduce with Today's build, hence re-opening this ticket.

![image](https://user-images.githubusercontent.com/63310656/108732422-8dff8280-7553-11eb-9401-41ffcaa40ba6.png)

**Comment by bayk** [comment]
Yes, I see that problem. The new account name didn't reach the mwc713 request.  But it is hard to fix until new wallet creation bug will be fixed.
@sarawut11   - FYI

**Comment by bayk** [comment]
@sarawut11 , seems like the problem on your side.  This problem happens when Output page refreshing outputs.  requestOutputs  function is called with empty account value. 

Looks like there is some initialization race condition. Other pages looks fine. From the logs I see issues with outputs only.

I can ignore that call,  but I think it is better to understand why the account is empty. For example the accounts list is not initialized yet. In this case you might need to cal this method later to have a valid state.

**Comment by vinayaga07** [comment]
Verified with the latest build, hence closing this ticket.
