### ISSUE TITLE
After login into QT wallet, the "Transcations" page number of confirmation details are not getting displayed

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#718]
**Description:**
After login into QT wallet, the "Transcations" page number of confirmation details are not getting displayed whereas after a page refresh it is getting displayed.

**After Login (without clicking refresh button)**
![image](https://user-images.githubusercontent.com/63310656/104942404-6a886b80-59da-11eb-9964-1563e7ec3a40.png)

**After clicking the Refresh button.**
![image](https://user-images.githubusercontent.com/63310656/104942420-6fe5b600-59da-11eb-9d4b-67dad188991c.png)

**Expected Result:**
 After login into QT wallet, the "Transactions" page should display a number of confirmation details.

**Comment by bayk** [comment]
@vinayaga07 ,  such behavior is expected if node is not healthy. 
If you run your local node, then it is expected, it takes time to find peers and because of that number of confirmations will not be shown. 
If you running default settings and using the cloud mwc node (AWS instance at Canada), then you might getting a timeout on the init call.  That problem I try fix. For node info I add retry, that should help.  I don't want to increase the timeouts because it will slowdown handling cases when the node is offline. Please check if it helps.

**Comment by vinayaga07** [comment]
Closing this ticket as per the previous comment.
