### ISSUE TITLE
Introduce Bech32 addresses instead of Tor and MQS URI.

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#756]
Both mwc-wallet & mwc713 are using  URI for MQS and TOR connections.  Both MQS and TOR addresses are public keys.  More traditional way of address format is Bech32 (it can be transsformed to and from PK, so we can convert addresses that we have now into Bech32). 
We can have one type of address for MQS and another type for Tor, Slatepack and files.  Because of prefix it will be easy to distinguish them.  The prefix should start from 'mwc', then letter of address type and network.

On mwc-wallet side we already has bitcoin Bech32 address implementation that adopted for different coins. That solution can be adopted for MWC addresses as well.

**Comment by suemto** [comment]
It's good to use Bech32 format to code all kinds of addresses, with the nice native prefix and well checksum.

Some comments/proposals here:
1. Instead of define and announce a(or a series of) much formal MWC address, I would prefer a less formal way for them, to reserve the MWC address ONLY as NIT address, since NIT address is the only native address on the chain and we should keep this direction for the future. (I'm expecting NIT address will obsolete all other addresses in MWC in the future.)
2. Another reason is all these existing addresses are not the MWC chain related address, they only make sense on the wallet side. And even the TOR address and Slatepack address are in the different Elliptic-Curve from the chain.
3. Based on above consideration, I propose to reserve "mwc1..." and not used here. And the less formal prefixes (mqs/mqst, tor/tort, sla/slat) are proposed here, "t" is for Testnet. All these prefixes are much instinctive and well self-expressed.

Giving an unique and well known address prefix is quite important for the branding of MWC coin, so let's be more careful on this and avoid any possible confusing of all kinds of addresses of MWC.

**Comment by bayk** [comment]
@jbyrer   @vinayaga07   @yyangli     -  Just FYI.  There was a discussion about how to present addresses that we have for the wallet. So we are keeping transport addresses separately form MWC blockchain.  Interactive Transaction doesn't have the address and our users should understand the difference. 
For NIT transaction address make sense because it really exist on the chain.
