### ISSUE TITLE
Mobile Wallet, login page, status

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#767]
On login we need status line similar to what Desktop wallet has. 
The login might take a while and we better to show user the status about the progress.
Please check Desktop wallet, you will see what I mean.

**Comment by sarawut11** [comment]
@bayk It was already implemented. If you didn't see it, it is because it is too fast so nothing to show before go to the wallet.
You may see in the previous demos in the engineering meeting.
Or you can try to open the wallet after a few hours of previous open.
Since if you open the wallet after a few mins of previous open, it is too fast so nothing to show.

**Comment by bayk** [comment]
@sarawut11 ,  Desktop has more status information now. For example it is showing "Tor is starting".  It wasn't shown  on the last build.

**Comment by vinayaga07** [comment]
Verified.
