### ISSUE TITLE
Mobile wallet Login screen, Build version UI/UX needs corrections.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#780]
**Description:**
In the Mobile wallet Login screen, the Build version display needs corrections.

**Actual Result:**
MWC QT WALLET V1.0 DEV BUILD

**Expected Result:**
v 1.0.0 

![image](https://user-images.githubusercontent.com/63310656/109175381-bda8c780-77ab-11eb-9cd7-16be8718f487.png)

**Comment by bayk** [comment]
@sarawut11 , where are you getting the version?  Is it mobile app version or you are reading it similar to desktop wallet?

**Comment by sarawut11** [comment]
I'm reading it similar to desktop wallet @bayk 
```config.get_APP_NAME() + " v" + config.getBuildVersion()```

**Comment by bayk** [comment]
I make it to match what desktop wallet version we have. But please note that for the desktop build pipeline building the beta and release version, so that value is generated by build pileline.
For the mobile wallet we are building only testing version, for the release we will need to build manually with production certificates.  That is why there is no version generation is done for the mobile wallet.

**Comment by vinayaga07** [comment]
Closing as per the above comments.
