### ISSUE TITLE
Mobile wallet - Creating wallet (Unsafe saving)

### ISSUE THREAD

**Issue by vek-kal** [mwcproject/mwc-qt-wallet#811]
On the mobile wallet, i was creating a wallet and needed to copy back the seed phrase, and then switching between my apps running for whatever reasons, when i goes to my wallet to recopy all the next seed phrase, it appears that the mwc wallet saved my wallet without recopying the word.

**Comment by vek-kal** [comment]
It's seems quite hard to reproduce this issue.

**Comment by bayk** [comment]
It is known issue and we can't fix that nicely. If you close app during creation that phase, the wallet will be created.
I don't want to add additional logic that will delete such accidentally created wallet because of such feature destructive nature .  Postponing wallet seed file creation is not good solution as well.  So far we don't have much complains about that, let's keep it as it is.
